version: "3.9"

services:
  # PostgreSQL (Auth & Security Roles)
  auth-db:
    image: postgres:15-alpine
    container_name: church-auth-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # MongoDB (Letters, News, Gallery Metadata)
  content-db:
    image: mongo:latest
    container_name: church-content-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # MinIO (The File Server for Attachments/Images)
  file-server:
    image: quay.io/minio/minio
    container_name: church-file-server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # API Port (Your Go services connect here)
      - "9001:9001" # Console Port (You log in here to see files)
    volumes:
      - minio_data:/data

volumes:
  auth_db_data:
  mongo_data:
  minio_data: # New volume for your documents and images