# Use the official Golang image
#FROM golang:1.24-alpine

# Set the working directory inside the container
#WORKDIR /app

# Copy go.mod and go.sum files first (for caching)
#COPY go.mod go.sum ./
#RUN go mod download

# Copy the rest of the source code
#COPY . .

# Build the application
#RUN go build -o main ./cmd/main.go

# Expose the port (9002 for letters, 9001 for news, etc.)
#EXPOSE 8081

# Run the binary
#CMD ["./main"]